server:
  port: 8080

spring:
  datasource:
    name: test
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://116.62.195.10:3306/hotel?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: hotel
    password: hotel_123456




    # 使用druid数据源
#    type: com.alibaba.druid.pool.DruidDataSource
#    filters: stat
#    maxActive: 20
#    initialSize: 1
#    maxWait: 60000
#    minIdle: 1
#    timeBetweenEvictionRunsMillis: 60000
#    minEvictableIdleTimeMillis: 300000
#    validationQuery: select 'x'
#    testWhileIdle: true
#    testOnBorrow: false
#    testOnReturn: false
#    poolPreparedStatements: true
#    maxOpenPreparedStatements: 20
mybatis:
  mapper-locations: classpath*:mybatis/mapper/*.xml  # 扫描mapping文件
  type-aliases-package: com.springboot.modal    # 扫描实体类包，简化reultType 实体类名称
  configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   # spring boot集成mybatis的方式打印sql


#logging:
#    config: classpath:logback.xml
